version: '3'
services:
  frontend:
    build:
      context: ./
    ports:
      - "5137:5137"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend # Adjust this path
    ports:
      - "3000:3000"
